# MIT License
# Copyright (C) 2020 Tymko Oleg <olegtymko@yandex.ru> and contributors
# All rights reserved.

name: Тестирование
# Любой пуш и pr в проекте
on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
        oscript_version: ['1.8.3', 'stable']
        
    steps:
      # Загрузка проекта
      - name: Актуализация
        uses: actions/checkout@v2

      # Установка OneScript конкретной версии
      - name: Установка OneScript
        uses: otymko/setup-onescript@v1.1
        with:
          version: ${{ matrix.oscript_version }}

      # Установка зависимостей пакета
      - name: Установка зависимостей
        run: |
          opm install opm
          opm install -l --dev
          
      # Задача тестирования, в результате ожидается успешное выполнение
      - name: Тестирование
        run: oscript ./tasks/test.os

      # Публикация результатов тестирования
      - name: Publish Test Report (Ubuntu)
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always() && matrix.os == 'ubuntu-latest'
        with:
          junit_files: '**/out/tests.xml'
      - name: Publish Test Report (MacOS & Windows)
        uses: EnricoMi/publish-unit-test-result-action/composite@v2
        if: always() && matrix.os != 'ubuntu-latest'
        with:
          junit_files: '**/out/tests.xml'